import { NavBar } from '@/components/NavBar/NavBar'
import './globals.css'
import { Inter } from 'next/font/google'
import { TopNavBar } from '@/components/TopNavBar/TopNavBar'
import { Footer } from '@/components/Footer/Footer'
import { CartContextProvider, useCartContext } from '@/context/CartContext'
import { CartView } from '@/components/CartView'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartContextProvider>
          <header className='fixed z-[8888] w-full top-0'>
            <NavBar/>
          </header>
          <main>
            {children}
            <CartView/>
          </main>
          <Footer/>
        </CartContextProvider>
      </body>
    </html>
  )
}
